post http://localhost:3003/api/blogs/6413156c53f536a044217aea/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVydXNlciIsImlkIjoiNjQwYWY1Y2NjZjg4MWFjMjEzMDI2NWI5IiwiaWF0IjoxNjgxNTc0MjQxLCJleHAiOjE2ODE1Nzc4NDF9.JVyrhVxBmc4tQl23g12nrJBQ0kgBz_T3v2Y5IgpVh7U

{
    "content": "pls man"
}